nameOverride: ""
fullnameOverride: ""

nodeSelector: {}
tolerations: []
affinity: {}
podAnnotations: {}

imagePullSecrets: {}

serviceAccount:
  create: false
  annotations: {}

image:
  repository: docker.wiseflow.io/k8s/graphjin
  tag: latest
  pullPolicy: IfNotPresent

terminationGracePeriodSeconds: 60

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

disruptionBudget:
  enabled: true
  maxUnavailable: 1

resources: {}
  
service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  # annotations: 
  #   kubernetes.io/ingress.class: "nginx"
  # hosts:
  #   - host: gql.test.eu.wiseflow.io
  #     paths: 
  #       - /
  # tls:
  #   - hosts:
  #     - gql.test.eu.wiseflow.io
  #     secretName: graphjin-test-tls

config:
  production: true
  host_port: 0.0.0.0:8080
  auth:
    jwt: 
      public_key_file: /keys/public.pem

database:
  host: ""
  port: 3306
  user: ""
  password: ""

jwt:
  publicKey: ""

queries:
  flowParticipant.yaml: |
    name: participant
    query: |-
      query participant @opa(policy: "/test/test/test") {
        user: me {
          id
          firstName
          lastName
          participant: flowParticipantRecord(where: {flowId: $flowId}) {
            number
          }
        }
      }

    vars: |-
      {
        "flowId": 0.0
      }

opa:
  enabled: true
  image:
    tag: ""
  distributor:
    url: ""
    name: "graphjin"
    resource: ""
  data:
    graphQLUrl: "http://graphjin.test-graphjin-internal"
    vpnHost: "europe-test-vpn.wiseflow.net"

  annotations: {}
