nameOverride: ""
fullnameOverride: ""

nodeSelector: {}
tolerations: []
affinity: {}
podAnnotations: {}

imagePullSecrets: {}

serviceAccount:
  create: false
  annotations: {}

terminationGracePeriodSeconds: 60

# determines if the dev.yml or prod.yml should be used,
# and where to locate the config (external/ or internal/)
external: true
environment: "test"

gitSync:
  repo: ""
  intervalSeconds: "300"
  github:
    username: ""
    personalAccessToken: "secret"
  resources:
    limits:
      memory: 10Mi
    requests:
      cpu: 20m
      memory: 100Mi
      ephemeral-storage: 50Mi

graphjin:
  image:
    repository: docker.wiseflow.io/k8s/graphjin
    tag: latest
    pullPolicy: IfNotPresent

  resources:
    limits:
      memory: 1000Mi
    requests:
      cpu: 200m
      memory: 1000Mi
      ephemeral-storage: 10Mi

  database:
    host: ""
    port: 3306
    user: ""
    password: ""

opaClient:
  enabled: true
  image:
    tag: ""
  distributor:
    url: ""
    name: "graphjin"
    resource: ""
  data:
    graphQLUrl: "http://graphjin.test-graphjin-internal"
    vpnHost: "europe-test-vpn.wiseflow.net"

  annotations: {}
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi
      ephemeral-storage: 100Mi

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

disruptionBudget:
  enabled: true
  maxUnavailable: 1

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  # annotations: 
  #   kubernetes.io/ingress.class: "nginx"
  # hosts:
  #   - host: gql.test.eu.wiseflow.io
  #     paths: 
  #       - /
  # tls:
  #   - hosts:
  #     - gql.test.eu.wiseflow.io
  #     secretName: graphjin-test-tls



