{{- if .Values.opaClient.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graphjin.fullname" . }}-opa
  labels:
    helm.sh/chart: {{ include "graphjin.chart" . }}
    {{ include "graphjin.labels" . | nindent 4 }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.yaml: |
    services:
    - name: distributor
      url: {{ .Values.opaClient.distributor.url }}

    discovery:
      resource: {{ default (printf "/configuration/%s/discovery.tar.gz" ( .Chart.Name )) .Values.opaClient.distributor.resource }}
      service: distributor
  data.json: |
    {{ .Values.opaClient.data | toJson }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graphjin.fullname" . }}-git-sync
  labels:
    helm.sh/chart: {{ include "graphjin.chart" . }}
    {{ include "graphjin.labels" . | nindent 4 }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  .gitsparse: |
    {{ printf "/%s/%s/" .Values.environment (ternary "external" "internal" .Values.external) }}