apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graphjin.fullname" . }}-jwt-public-key
  labels:
    {{- include "graphjin.labels" . | nindent 4 }}
data: 
  publicKey: {{ .Values.jwt.publicKey | quote }}
---
{{- if .Values.opa.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graphjin.fullname" . }}-opa
  labels:
    helm.sh/chart: {{ include "graphjin.chart" . }}
    {{ include "graphjin.labels" . | nindent 4 }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.yaml: |
    services:
    - name: distributor
      url: {{ .Values.opa.distributor.url }}

    discovery:
      resource: {{ default (printf "/configuration/%s/discovery.tar.gz" ( .Chart.Name )) .Values.opa.distributor.resource }}
      service: distributor
  data.json: |
    {{ .Values.opa.data | toJson }}
{{- end }}
---
{{- if .Values.queries }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graphjin.fullname" . }}-queries
  labels:
    {{- include "graphjin.labels" . | nindent 4 }}
data:
  {{ .Values.queries | toYaml | nindent 2 }}
{{ end }}
---
{{- if .Values.scripts }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graphjin.fullname" . }}-scripts
  labels:
    {{- include "graphjin.labels" . | nindent 4 }}
data:
  {{ .Values.scripts | toYaml | nindent 2 }}
{{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graphjin.fullname" . }}-config
  labels:
    {{- include "graphjin.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.config | toYaml | nindent 4 }}