apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "graphjin.fullname" . }}
  labels:
    {{- include "graphjin.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "graphjin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "graphjin.selectorLabels" . | nindent 8 }}
      annotations: 
        checksum/config: {{ toJson .Values.config | sha256sum | quote }}
        checksum/jwt: {{ .Values.jwt.publicKey | sha256sum | quote }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      volumes:
        - name: "jwt-public-key"
          configMap:
            name: {{ include "graphjin.fullname" . }}-jwt-public-key
        - name: "config"
          configMap:
            name: {{ include "graphjin.fullname" . }}-config
        {{- if .Values.queries }}
        - name: "queries"
          configMap:
            name: {{ include "graphjin.fullname" . }}-queries
        {{- end }}
        {{- if .Values.scripts }}
        - name: "scripts"
          configMap:
            name: {{ include "graphjin.fullname" . }}-scripts
        {{- end }}
        {{- if .Values.opa.enabled }}
        - name: opa-config
          configMap:
            name: {{ include "graphjin.fullname" . }}-opa
        {{- end }}
      serviceAccountName: {{ include "graphjin.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GJ_DATABASE_HOST
              value: {{ .Values.database.host | quote }}
            - name: GJ_DATABASE_PORT
              value: {{ .Values.database.port | quote }}
            - name: GJ_DATABASE_USER
              value: {{ .Values.database.user | quote }}
            - name: GJ_DATABASE_PASSWORD
              value: {{ .Values.database.password | quote }}
            - name: GO_ENV
              value: {{ ternary "production" "development" .Values.config.production | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.external.port }}
              protocol: TCP
            - name: httpInternal
              containerPort: {{ .Values.service.internal.port }}
              protocol: TCP
          volumeMounts:
            - name: "jwt-public-key"
              subPath: publicKey
              mountPath: /config{{ .Values.config.auth.jwt.public_key_file }}
            - name: "config"
              subPath: config.yaml
              mountPath: /config/{{ ternary "prod" "dev" .Values.config.production }}.yaml
            {{- if .Values.queries }}
            {{- range $k, $v := .Values.queries }}
            - name: "queries"
              subPath: {{ $k }}
              mountPath: /config/queries/{{ $k }}
            {{- end }}
            {{- end }}
            {{- if .Values.scripts }}
            {{- range $k, $v := .Values.scripts }}
            - name: "scripts"
              subPath: {{ $k }}
              mountPath: /config/scripts/{{ $k }}
            {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.opa.enabled }}
        - name: opa
          image: openpolicyagent/opa:{{ default "0.35.0" .Values.opa.image.tag }}
          ports:
            - name: http
              containerPort: 8181
              protocol: TCP
          args:
          - "run"
          - "--ignore=.*"  # exclude hidden dirs created by Kubernetes
          - "--server"
          - "--log-format=json"
          - "--config-file=/app/config.yaml"
          - "/app/data.json"
          volumeMounts:
          - readOnly: true
            mountPath: /app
            name: opa-config
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
        {{- end}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
