apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "graphjin.fullname" . }}
  labels:
    {{- include "graphjin.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "graphjin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "graphjin.selectorLabels" . | nindent 8 }}
      annotations: 
        checksum/config: {{ toJson .Values.config | sha256sum | quote }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      serviceAccountName: {{ include "graphjin.serviceAccountName" . }}
      containers:
        - name: git-sync
          image: k8s.gcr.io/git-sync:v3.1.3
          volumeMounts:
          - name: config
            mountPath: /tmp/git
          - name: sparse
            mountPath: /etc/git-sync/
          env:
          - name: GIT_SYNC_REPO
            value: {{ .Values.gitSync.repo }}
          - name: GIT_SYNC_WAIT
            value: {{ .Values.gitSync.intervalSeconds }}
          - name: GIT_SYNC_DEST
            value: git-sync
          - name: GIT_SYNC_SPARSE_CHECKOUT_FILE
            value: /etc/git-sync/.gitsparse
          resources:
            {{- toYaml .Values.gitSync.resources | nindent 12 }}
        - name: graphjin
          image: "{{ .Values.graphjin.image.repository }}:{{ .Values.graphjin.image.tag }}"
          imagePullPolicy: {{ .Values.graphjin.image.pullPolicy }}
          args:
            - "serv"
            - "--path"
            - {{ printf "/config/%s/%s/" .Values.environment (ternary "external" "internal" .Values.external) | quote }}
            - {{ ternary "prod.yml" "dev.yml" .Values.external | quote }}
          env:
            - name: GJ_DATABASE_HOST
              value: {{ .Values.graphjin.database.host | quote }}
            - name: GJ_DATABASE_PORT
              value: {{ .Values.graphjin.database.port | quote }}
            - name: GJ_DATABASE_USER
              value: {{ .Values.graphjin.database.user | quote }}
            - name: GJ_DATABASE_PASSWORD
              value: {{ .Values.graphjin.database.password | quote }}
            - name: GO_ENV
              value: {{ ternary "production" "development" .Values.external | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.graphjin.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config
        {{- if .Values.opaClient.enabled }}
        - name: opa
          image: openpolicyagent/opa:{{ default "0.35.0" .Values.opaClient.image.tag }}
          ports:
            - name: http
              containerPort: 8181
              protocol: TCP
          args:
          - "run"
          - "--ignore=.*"  # exclude hidden dirs created by Kubernetes
          - "--server"
          - "--log-format=json"
          - "--config-file=/app/config.yaml"
          - "/app/data.json"
          volumeMounts:
          - readOnly: true
            mountPath: /app
            name: opa-config
          resources:
            {{- toYaml .Values.opaClient.resources | nindent 12 }}
        {{- end}}
      volumes:
        - name: config
          emptyDir: {}
        - name: git-sync
          configMap:
            name: sherlock-config
        {{- if .Values.opaClient.enabled }}
        - name: opa-config
          configMap:
            name: {{ include "graphjin.fullname" . }}-opa
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
