apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "graphjin.fullname" . }}-git-sync
  labels:
    app.kubernetes.io/name: {{ include "graphjin.name" . }}
    helm.sh/chart: {{ include "graphjin.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  personalAccessToken: {{ .Values.gitSync.github.personalAccessToken }}