apiVersion: v1
kind: Service
metadata:
  name: {{ include "graphjin.fullname" . }}
  labels:
    {{- include "graphjin.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.external.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "graphjin.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "graphjin.fullname" . }}-internal
  labels:
    {{- include "graphjin.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.internal.port }}
      targetPort: http-internal
      protocol: TCP
      name: http
  selector:
    {{- include "graphjin.selectorLabels" . | nindent 4 }}
